# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=test
      sonar.projectName=test

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'https://sonar.supervity.ai/projects'
    arguments: 'test'
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
